#!/usr/bin/env python3
"""CI check for ignored pending-issue markers, and index generator
(defer-issues skill).

Default mode scans the files edited in a commit range for
`TODO [issue-<id>](...)` markers that were *ignored*: the file changed, but the
marker's issue was neither touched (no marker line added/removed) nor mentioned
in any commit message in the range. Repeatedly ignored markers are candidates
for escalation to a path-scoped rule (.claude/rules/issue-<id>.md), which is
auto-injected into context on the next edit and therefore carries more weight
than the comment.

`--index` mode instead regenerates the index file (ISSUES.md) from the record
files, which are the source of truth — so an index line can never outlive,
contradict, or go missing from its record.

Every path is resolved against `git rev-parse --show-toplevel`, so both modes
behave identically from any directory inside the repo. Files whose markers are
illustrative rather than real — documentation of the marker format, fixtures
that embed one — are listed as globs in `.defer-issues-ignore` at the repo root
and skipped entirely.

Pure standard library; needs only `git` on PATH.

Usage:
  python3 scripts/check_todo_markers.py [--base <ref>] [--escalate] [--quiet]
  python3 scripts/check_todo_markers.py --index [--check] [--quiet]

  --base REF   Range to inspect is REF...HEAD (default: HEAD~1) — three dots,
               so it diffs against the merge base and a branch that is behind
               REF is not blamed for REF's own edits. In CI: --base origin/main.
  --escalate   Write a thin escalation rule for each ignored marker
               (skipped if a rule for that id already exists).
  --index      Rewrite ISSUES.md from the record files in --issues-dir. Prose
               above the generated-section sentinel is kept verbatim;
               everything below it is generated and sorted by id.
  --check      With --index: report drift and exit 1 instead of rewriting.
  --quiet      Only print ignored markers / escalations / index changes.

Exit code: 1 if any ignored marker was found, or (with --index --check) if the
index is out of date — so CI can flag either. Otherwise 0.
"""
import argparse
import difflib
import re
import subprocess
import sys
from fnmatch import fnmatch
from pathlib import Path

MARKER = re.compile(r"TODO \[issue-([\w-]+)\]\(([^)]*)\):\s*(.*)")
# Literal prefix for `git grep -F`. -F is required, not stylistic: the marker
# contains [...], which git grep reads as a character class and rejects.
MARKER_LITERAL = "TODO [issue-"
# `# Pending: <id> — <title>` — the first heading of every record file, per
# references/{comment,rule}-template.md. The id there is `#142` when
# GitHub-paired and `local-3` when not; the filename is authoritative either
# way, so only the title is taken from here.
HEADING = re.compile(r"^#\s+Pending:\s*\S+\s+(?:—|--)\s+(.+?)\s*$", re.M)
GH_URL = re.compile(r"https://github\.com/[\w.-]+/[\w.-]+/issues/\d+")
# Everything below this line in the index file is regenerated; everything above
# it is human-written prose and is preserved verbatim.
SENTINEL = ("<!-- generated by check_todo_markers.py --index — "
            "edit the record files, not this list -->")
# Repo-root file listing glob patterns whose markers are illustrative, not real
# (documentation showing the marker format, eval fixtures embedding one).
IGNORE_FILE = ".defer-issues-ignore"
# Fixed by the skill, not configurable: rules live where the harness injects
# them from, and the index is one known file at the repo root.
RULES_DIR = ".claude/rules"
ISSUES_FILE = "ISSUES.md"


def repo_root():
    """Repo root, so every path resolves the same from any cwd.

    `git diff --name-only` and `git grep --full-name` both emit root-relative
    paths; testing those against the *current* directory made the check a
    silent no-op whenever it ran from a subdirectory.
    """
    p = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                       capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit(f"not inside a git repository: {p.stderr.strip()}")
    return Path(p.stdout.strip())


def git(root, *args):
    p = subprocess.run(["git", "-C", str(root), *args],
                       capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit(f"git {' '.join(args)} failed: {p.stderr.strip()}")
    return p.stdout


def git_grep(root, *args):
    """git grep, tolerating exit 1 (no matches) rather than treating it fatal.

    `-C root` matters twice over: git grep searches from the cwd down, so from
    a subdirectory it would quietly miss every marker outside it.
    """
    p = subprocess.run(["git", "-C", str(root), "grep", *args],
                       capture_output=True, text=True)
    return p.stdout


def load_ignores(root):
    """Glob patterns from .defer-issues-ignore; blank lines and `#` skipped.

    Without this, a file that *documents* the marker format is indistinguishable
    from one that carries a real marker, so editing the docs reports a bogus
    IGNORED in CI.
    """
    try:
        text = (root / IGNORE_FILE).read_text()
    except OSError:
        return []
    return [ln.strip() for ln in text.splitlines()
            if ln.strip() and not ln.lstrip().startswith("#")]


def is_ignored(path, patterns):
    # fnmatch treats `*` as matching `/` too, so `skills/*/x.md` also matches
    # deeper paths — deliberate here: these patterns name whole doc areas.
    return any(fnmatch(path, pat) for pat in patterns)


def markers_in(root, path):
    try:
        text = (root / path).read_text(errors="replace")
    except OSError:
        return []
    out = []
    for m in MARKER.finditer(text):
        summary = re.split(r"\s+—\s+", m.group(3))[0].strip()
        out.append({"id": m.group(1), "file": path, "summary": summary})
    return out


# --- index generation -------------------------------------------------------

def sort_key(iid):
    """Natural sort: local-2 before local-11, and 9 before 142."""
    return tuple((int(c), "") if c.isdigit() else (-1, c)
                 for c in re.split(r"(\d+)", iid) if c)


def collect_records(root, issues_dir):
    """One entry per issue id: (id, record path, title, gh url or None).

    Every issue's record lives in `issues_dir`; a rule in RULES_DIR is an
    anchor pointing at one, never the issue itself, so the record always wins.
    RULES_DIR is scanned anyway for the dangling case — a rule whose record is
    missing is indexed off the rule and warned about, rather than vanishing
    from the index unmentioned.
    """
    found, recorded = {}, set()
    for d in (RULES_DIR, issues_dir):  # issues_dir second so the record wins
        for f in sorted((root / d).glob("issue-*.md")):
            iid = f.stem[len("issue-"):]
            text = f.read_text(errors="replace")
            m = HEADING.search(text)
            if not m:
                print(f"warning: {f.relative_to(root)} has no "
                      f"'# Pending: <id> — <title>' heading; using the id as "
                      f"its summary", file=sys.stderr)
            gh = GH_URL.search(text)
            found[iid] = {
                "id": iid,
                "path": f.relative_to(root).as_posix(),
                "title": m.group(1) if m else iid,
                "gh": gh.group(0) if gh else None,
            }
            if d == issues_dir:
                recorded.add(iid)
    for iid in sorted(set(found) - recorded, key=sort_key):
        print(f"warning: {RULES_DIR}/issue-{iid}.md is a dangling anchor — no "
              f"record at {issues_dir}/issue-{iid}.md; indexing the rule "
              f"instead", file=sys.stderr)
    return [found[k] for k in sorted(found, key=sort_key)]


def render_index(root, records):
    """The full index file: preserved prose + sentinel + generated list."""
    path = root / ISSUES_FILE
    preamble = f"# Pending issues\n\nRecord files are the source of truth.\n\n"
    if path.exists():
        old = path.read_text()
        if SENTINEL in old:
            preamble = old.split(SENTINEL)[0]
        else:
            # First run against a hand-written index: keep everything above the
            # first list item or section heading, drop the hand-written list.
            lines = old.splitlines(keepends=True)
            cut = next((i for i, ln in enumerate(lines)
                        if ln.startswith("- [") or ln.startswith("## ")),
                       len(lines))
            preamble = "".join(lines[:cut])
    preamble = preamble.rstrip("\n") + "\n\n"
    body = "".join(
        f"- [{r['id']}]({r['path']}) {r['title']}"
        + (f" ([gh]({r['gh']}))" if r["gh"] else "")
        + "\n"
        for r in records)
    return preamble + SENTINEL + "\n\n" + (body or "_None._\n")


def run_index(root, args):
    records = collect_records(root, args.issues_dir)
    path = root / ISSUES_FILE
    new = render_index(root, records)
    old = path.read_text() if path.exists() else ""
    if new == old:
        if not args.quiet:
            print(f"OK: {ISSUES_FILE} matches "
                  f"{len(records)} record file(s)")
        return 0
    diff = "".join(difflib.unified_diff(
        old.splitlines(keepends=True), new.splitlines(keepends=True),
        fromfile=f"a/{ISSUES_FILE}", tofile=f"b/{ISSUES_FILE}"))
    if args.check:
        print(f"DRIFT: {ISSUES_FILE} does not match the record files; "
              f"run --index to regenerate\n{diff}")
        return 1
    path.write_text(new)
    print(f"INDEXED: wrote {ISSUES_FILE} "
          f"from {len(records)} record file(s)")
    if not args.quiet:
        print(diff, end="")
    return 0


# --- ignored-marker check ---------------------------------------------------

def run_check(root, args):
    rules_dir = root / RULES_DIR
    rng = f"{args.base}..HEAD"
    # One repo-wide scan, reused for the prefilter below and for escalation
    # paths; bucket every marker-carrying file by issue id.
    files_by_id = {}
    # --full-name keeps paths repo-root-relative, matching `git diff --name-only`;
    # -I skips binaries, whose "Binary file <path> matches" line has no :n: fields.
    # Ignores are applied at the scan, not at the report, so an ignored path can
    # never leak into an --escalate rule's `paths:` either.
    ignores = load_ignores(root)
    for line in git_grep(root, "--full-name", "-nIF", MARKER_LITERAL).splitlines():
        path, _, text = line.split(":", 2)
        m = MARKER.search(text)
        if m and not is_ignored(path, ignores):
            files_by_id.setdefault(m.group(1), []).append(path)

    carriers = {f for paths in files_by_id.values() for f in paths}
    # `base...HEAD`, not `base HEAD`: three dots diff against the merge base, so
    # a branch that is merely *behind* base isn't blamed for base's own edits.
    # Two dots made every file main touched look like this PR's work.
    span = f"{args.base}...HEAD"
    # Only edited files that actually carry a marker are worth reading — a PR
    # touching lockfiles and minified assets otherwise reads all of them.
    # -z, because plain .split() shatters paths containing spaces and the
    # fragments then match nothing — another silently-clean miss.
    edited = [f for f in git(root, "diff", "--name-only", "-z", span).split("\0")
              if f in carriers and (root / f).is_file()]
    # -G restricts the patch to files whose added/removed lines match, and
    # --unified=0 drops context: a few hundred bytes instead of the full diff.
    diff = git(root, "diff", "--unified=0", "-GTODO \\[issue-", span)
    log = git(root, "log", "--format=%B", rng)
    # ids whose marker lines were added/removed anywhere in the range
    touched = set(re.findall(r"^[+-].*TODO \[issue-([\w-]+)\]", diff, re.M))

    ignored = []
    for f in edited:
        for mk in markers_in(root, f):
            # Delimited, not a substring: a bare `in` check let "local-12" in a
            # commit message satisfy a "local-1" marker, permanently exempting
            # every id that prefixes another. `issue-<id>` is subsumed by this.
            mentioned = re.search(rf"(?<![\w-]){re.escape(mk['id'])}(?![\w-])",
                                  log)
            if mk["id"] in touched or mentioned:
                continue
            ignored.append(mk)
            print(f"IGNORED: issue-{mk['id']} in {f} — {mk['summary']}")

    if not ignored:
        if not args.quiet:
            print(f"OK: no ignored pending-issue markers in {rng}")
        return 0

    if args.escalate:
        by_id = {}
        for mk in ignored:
            by_id.setdefault(mk["id"], mk)
        for iid, mk in by_id.items():
            rule = rules_dir / f"issue-{iid}.md"
            if rule.exists():
                if not args.quiet:
                    print(f"skip: {RULES_DIR}/issue-{iid}.md already exists")
                continue
            # every file currently carrying this marker, from the scan above
            paths = files_by_id.get(iid) or [mk["file"]]
            rules_dir.mkdir(parents=True, exist_ok=True)
            # Keep in sync with the "Escalation rule" section of
            # references/rule-template.md, which is canonical for this format.
            rule.write_text(
                "---\npaths:\n"
                + "".join(f'  - "{p}"\n' for p in paths)
                + "---\n"
                + f"# Pending: {iid} — {mk['summary']}\n"
                + "Escalated: the TODO marker for this issue was ignored in "
                  "a recent change.\n"
                + f"Full record: {args.issues_dir}/issue-{iid}.md\n\n"
                + "Relevant here? Invoke the defer-issues skill to resolve "
                  "it properly (gate,\nfix, verify, close). Not relevant? "
                  "Note it as pending in your final report.\n")
            print(f"ESCALATED: wrote {RULES_DIR}/issue-{iid}.md "
                  f"(paths: {', '.join(paths)})")

    return 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="HEAD~1")
    ap.add_argument("--escalate", action="store_true")
    ap.add_argument("--index", action="store_true",
                    help="regenerate the index file from the record files")
    ap.add_argument("--check", action="store_true",
                    help="with --index: report drift, don't rewrite")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--issues-dir", default="issues",
                    help="must match the skill's issues_dir metadata key")
    args = ap.parse_args()
    if args.check and not args.index:
        ap.error("--check only applies with --index")

    root = repo_root()
    return run_index(root, args) if args.index else run_check(root, args)


if __name__ == "__main__":
    sys.exit(main())
